### PR TITLE
Flare Revolver VFX replacement

### PR DESCRIPTION
**Pull request by nr42111**
[flarerev_sm.webm](https://github.com/user-attachments/assets/b6f90eef-7536-4bb4-8136-79cd97a65f97)

### CODE REVIEW

**Comment by KFPilot** [comment]
Explosion radius and decal do not match particle effect.

**Comment by nr42111** [comment]
current progress, going to change the texture of it to match the flare pistol's loaded projectile instead of black rod


[flare_sm3.webm](https://github.com/user-attachments/assets/c54200b8-3877-42ab-8e16-e3c39fd351cd)

**Comment by nr42111** [comment]
Updated to gold shell/round, i have a .dds that can be put into the files and change the look on the old black rod to be that.

[flare_sm4.webm](https://github.com/user-attachments/assets/6e95696a-1660-42c6-9af8-e9aa7cfa87c0)

**Review by KFPilot — APPROVED** [review]
Looks good.

**Pull request merged**
